---
- name: Run apt upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Run apt install
  apt:
    name:
      - git
      - curl
      - vim-gtk
      - ack
      - entr
      - gcc
      - gdb
      - editorconfig
      - moreutils
      - xclip
      - trash-cli
      - golang-go
      - nodejs
      - npm
      - arduino
      - gnome-disk-utility
      - gparted
      - xfce4-clipman
      - network-manager-openvpn-gnome
      - python3-pip
      - obs-studio
      - ffmpeg
      - sqlite3
      - libsqlite3-dev
      - shellcheck
      - ruby
      - ruby-dev
      - htop
      - net-tools
      - youtube-dl
      - wireshark
      - thunderbird
      - firefox
      - tree
      - ansible-lint
    state: latest
    update_cache: yes

- name: Run pip install
  pip:
    name: ansible
    state: latest

- name: Run gem install
  gem:
    name: mailcatcher
    state: latest

- name: Download vgrep
  git:
    repo: https://github.com/vrothberg/vgrep
    dest: /tmp/vgrep
  register: vgrep_source

- name: Build vgrep
  make:
    chdir: /tmp/vgrep
    target: build
  when: vgrep_source.changed

- name: Install vgrep
  make:
    chdir: /tmp/vgrep
    target: install
  when: vgrep_source.changed
